### ISSUE TITLE
KeyError: 'delete_outdated_inbound'

### ISSUE THREAD

**Issue by alarig** [mautrix/python#154]
Hello,

When restarting the signal bridge, I get this stacktrace (Unexpected error in initialization):
```python
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mautrix/util/program.py", line 101, in _prepare
    self.prepare()
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/bridge.py", line 133, in prepare
    self.prepare_bridge()
  File "/usr/lib/python3.11/site-packages/mautrix_signal/__main__.py", line 64, in prepare_bridge
    super().prepare_bridge()
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/bridge.py", line 202, in prepare_bridge
    self.matrix = self.matrix_class(bridge=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix_signal/matrix.py", line 57, in __init__
    super().__init__(bridge=bridge)
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/matrix.py", line 182, in __init__
    self.e2ee = EncryptionManager(
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/bridge/e2ee.py", line 128, in __init__
    self.delete_outdated_inbound = del_cfg["delete_outdated_inbound"]
                                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ruamel/yaml/comments.py", line 842, in __getitem__
    return ordereddict.__getitem__(self, key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'delete_outdated_inbound'
```

The issue seems to be introduced in the commit https://github.com/mautrix/python/commit/ad42ba80605ff257ef7d490e1e7bdcfedaa9a320

**Comment by alarig** [comment]
Updating the configuration as follows works around the issue, but https://github.com/mautrix/signal/blob/master/mautrix_signal/example-config.yaml doesn’t mention it:
```yaml
bridge:
    encryption:
        delete_keys:
            periodically_delete_expired: false
```

**Comment by tulir** [comment]
That usually happens if you install incorrect versions of dependencies
