### ISSUE TITLE
 Exception in Matrix event handler: AttributeError: 'str' object has no attribute 'get' 

### ISSUE THREAD

**Issue by jaller94** [mautrix/python#92]
With a Telegram bridge fork of 0.10.2 (`mautrix==0.14.2`) we've seen these exceptions being thrown in irregular intervals:

```
This error happened several times:
* 2022-03-04 12:23:10,395
* 2022-03-04 12:23:41,433
* 2022-03-04 12:29:42,257
* 2022-03-04 12:30:38,447

```
[ERROR@mau.as] Exception in Matrix event handler
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mautrix/appservice/as_handler.py", line 239, in try_handle
    await handler_func(event)
  File "/usr/lib/python3.9/site-packages/mautrix/bridge/matrix.py", line 771, in int_handle_event
    await self.handle_leave(evt.room_id, UserID(evt.state_key), evt.event_id)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/matrix.py", line 196, in handle_leave
    await portal.leave_matrix(user, event_id)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 1387, in leave_matrix
    await self._send_state_change_message("leave", user, event_id)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 1211, in _send_state_change_message
    message = await self._get_state_change_message(event, user, **kwargs)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 1186, in _get_state_change_message
    tpl = self.get_config(f"state_event_formats.{event}")
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/portal.py", line 3151, in get_config
    local = util.recursive_get(self.local_config, key)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/recursive_dict.py", line 42, in recursive_get
    return recursive_get(next_data, next_key)
  File "/usr/lib/python3.9/site-packages/mautrix_telegram/util/recursive_dict.py", line 43, in recursive_get
    return data.get(key, None)
AttributeError: 'str' object has no attribute 'get'
```

**Comment by jaller94** [comment]
Sorry, I forgot that I had already filed this issue. Thanks for finding the 1st issue.
